### ISSUE TITLE
Incompatible with Lithium & FabricZero

### ISSUE THREAD

**Issue by Mewtwoy** [BoogieMonster1O1/ChunkErrors#1]
Mixin apply failed chunkerrors.mixins.json:NoiseChunkGeneratorMixin -> net.minecraft.class_3754: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_3754::modifyLowerInterpolated with priority 1000 cannot inject into net/minecraft/class_3754::method_16411(IIIDDDD)D merged by me.jellysquid.mods.lithium.mixin.gen.fast_noise_interpolation.NoiseChunkGeneratorMixin with priority 1000 [PREINJECT Applicator Phase -> chunkerrors.mixins.json:NoiseChunkGeneratorMixin -> Prepare Injections ->  -> redirect$bpa000$modifyLowerInterpolated(Lnet/minecraft/class_3537;I)Lnet/minecraft/class_3756; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3754::modifyLowerInterpolated with priority 1000 cannot inject into net/minecraft/class_3754::method_16411(IIIDDDD)D merged by me.jellysquid.mods.lithium.mixin.gen.fast_noise_interpolation.NoiseChunkGeneratorMixin with priority 1000 [PREINJECT Applicator Phase -> chunkerrors.mixins.json:NoiseChunkGeneratorMixin -> Prepare Injections ->  -> redirect$bpa000$modifyLowerInterpolated(Lnet/minecraft/class_3537;I)Lnet/minecraft/class_3756; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.10.8.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at com.fox2code.fabriczero.FabricZeroTransformerHook.transformClassBytes(FabricZeroTransformerHook.java:41) [fabriczero-0.2.0.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.10.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.minecraft.class_2794.<clinit>(class_2794.java:53) [intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_2378.method_29114(class_2378.java:232) [intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_2378$$Lambda$223/262535196.get(Unknown Source) [intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_2378.method_29110(class_2378.java:246) [intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_2378$$Lambda$2010/1483059446.accept(Unknown Source) [intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) [?:1.8.0_51]
	at net.minecraft.class_2378.<clinit>(class_2378.java:245) [intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) [intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) [intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]

**Comment by BoogieMonster1O1** [comment]
does it happen with only lithium installed?
